<h2>Edit Album</h2>

<form method="post">
	<input type="hidden" name="id" value="<?= $album->id ?>">

	<div class="form-group">
		<label>Title</label>
		<input type="text" name="title" class="form-control" value="<?= $album->title ?>">
	</div>

	<div class="form-group">
		<label>Artist</label>
		<input type="text" name="artist" class="form-control" value="<?= $album->artist ?>">
	</div>

	<input type="submit" value="Add Album" class="btn btn-primary">
</form>