<h2>Album List</h2>

<a href="<?= $this->url('album', ['action' => 'add']) ?>" class="btn btn-primary">+Add New Album</a>

<table class="table table-striped table-bordered">
	<tr>
		<th>ID</th>
		<th>Title</th>
		<th>Artist</th>
		<th>#</th>
	</tr>
	<?php foreach($albums as $album): ?>

		<tr>
			<td><?= $album->id ?></td>
			<td><?= $album->title ?></td>
			<td><?= $album->artist ?></td>
			<td>
				<a href="<?= $this->url('album', ['action' => 'edit','id'=>$album->id]) ?>">Edit</a>
				<a href="<?= $this->url('album', ['action' => 'delete','id'=>$album->id]) ?>" class="text-danger">Delete</a>
			</td>
			
		</tr>
	<?php endforeach ?>
</table>