<h2>Edit Artist</h2>

<form method="post">
	<input type="hidden" name="id" value="<?= $artist->id ?>">

	<div class="form-group">
		<label>Name</label>
		<input type="text" name="name" class="form-control" value="<?= $artist->name ?>">
	</div>

	<div class="form-group">
		<label>Bio</label>
		<input type="text" name="bio" class="form-control" value="<?= $artist->bio ?>">
	</div>

	<input type="submit" value="Add Artist" class="btn btn-primary">
</form>